# Use root/example as user/password credentials
version: "3.1"

services:
  node-app-1:
    image: node-app-1
    restart: always
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      my-network:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      my-network:

  # mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - mongo
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo-data:
    driver: local

networks:
  my-network:
